{
 "title": "smart-city",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "district",
    "query": {
     "query": "import \"influxdata/influxdb/schema\"\r\nschema.tagValues(\r\n  bucket: \"smartcity-bucket\",\r\n  tag: \"district\"\r\n)\r\n"
    }
   },
   {
    "name": "street",
    "query": {
     "query": "import \"influxdata/influxdb/schema\"\r\nschema.tagValues(\r\n  bucket: \"smartcity-bucket\",\r\n  tag: \"street\",\r\n  predicate: (r) => r.district == \"${district}\"\r\n)\r\n"
    }
   }
  ]
 },
 "panels": [
  { "title": "Traffic", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Traffic ",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "query": "from(bucket: \"smartcity-bucket\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"smartcity_sensors\" and\r\n    r.district == \"${district}\" and\r\n    r.street == \"${street}\" and\r\n    r.sensor == \"traffic\" and\r\n    r._field == \"value\"\r\n  )\r\n"
    },
    {
     "query": "threshold =\r\n  from(bucket: \"smartcity-bucket\")\r\n    |> range(start: -30d)\r\n    |> filter(fn: (r) =>\r\n      r._measurement == \"smartcity_config\" and\r\n      r._field == \"traffic\"\r\n    )\r\n    |> last()\r\n\r\nstart =\r\n  threshold\r\n    |> map(fn: (r) => ({\r\n        _time: v.timeRangeStart,\r\n        _value: r._value\r\n    }))\r\n\r\nstop =\r\n  threshold\r\n    |> map(fn: (r) => ({\r\n        _time: v.timeRangeStop,\r\n        _value: r._value\r\n    }))\r\n\r\nunion(tables: [start, stop])\r\n"
    }
   ]
  },
  {
   "title": "Current Traffic",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"smartcity-bucket\")\r\n  |> range(start: -5m)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"smartcity_sensors\" and\r\n    r.district == \"${district}\" and\r\n    r.street == \"${street}\" and\r\n    r.sensor == \"traffic\"\r\n  )\r\n  |> last()\r\n"
    },
    {
     "query": "threshold =\r\n  from(bucket: \"smartcity-bucket\")\r\n    |> range(start: -30d)\r\n    |> filter(fn: (r) =>\r\n      r._measurement == \"smartcity_config\" and\r\n      r._field == \"traffic\"\r\n    )\r\n    |> last()\r\n\r\nstart =\r\n  threshold\r\n    |> map(fn: (r) => ({\r\n        _time: v.timeRangeStart,\r\n        _value: r._value\r\n    }))\r\n\r\nstop =\r\n  threshold\r\n    |> map(fn: (r) => ({\r\n        _time: v.timeRangeStop,\r\n        _value: r._value\r\n    }))\r\n\r\nunion(tables: [start, stop])\r\n"
    }
   ]
  },
  {
   "title": "Mean Traffic",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"smartcity-bucket\")\r\n  |> range(start: v.timeRangeStart)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"smartcity_sensors\" and\r\n    r.district == \"${district}\" and\r\n    r.street == \"${street}\" and\r\n    r.sensor == \"traffic\"\r\n  )\r\n  |> mean()"
    },
    {
     "query": "threshold =\r\n  from(bucket: \"smartcity-bucket\")\r\n    |> range(start: -30d)\r\n    |> filter(fn: (r) =>\r\n      r._measurement == \"smartcity_config\" and\r\n      r._field == \"traffic\"\r\n    )\r\n    |> last()\r\n\r\nstart =\r\n  threshold\r\n    |> map(fn: (r) => ({\r\n        _time: v.timeRangeStart,\r\n        _value: r._value\r\n    }))\r\n\r\nstop =\r\n  threshold\r\n    |> map(fn: (r) => ({\r\n        _time: v.timeRangeStop,\r\n        _value: r._value\r\n    }))\r\n\r\nunion(tables: [start, stop])\r\n"
    }
   ]
  },
  {
   "title": "Min Traffic",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"smartcity-bucket\")\r\n  |> range(start: v.timeRangeStart)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"smartcity_sensors\" and\r\n    r.district == \"${district}\" and\r\n    r.street == \"${street}\" and\r\n    r.sensor == \"traffic\"\r\n  )\r\n  |> min()"
    },
    {
     "query": "threshold =\r\n  from(bucket: \"smartcity-bucket\")\r\n    |> range(start: -30d)\r\n    |> filter(fn: (r) =>\r\n      r._measurement == \"smartcity_config\" and\r\n      r._field == \"traffic\"\r\n    )\r\n    |> last()\r\n\r\nstart =\r\n  threshold\r\n    |> map(fn: (r) => ({\r\n        _time: v.timeRangeStart,\r\n        _value: r._value\r\n    }))\r\n\r\nstop =\r\n  threshold\r\n    |> map(fn: (r) => ({\r\n        _time: v.timeRangeStop,\r\n        _value: r._value\r\n    }))\r\n\r\nunion(tables: [start, stop])\r\n"
    }
   ]
  },
  {
   "title": "Max Traffic",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"smartcity-bucket\")\r\n  |> range(start: v.timeRangeStart)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"smartcity_sensors\" and\r\n    r.district == \"${district}\" and\r\n    r.street == \"${street}\" and\r\n    r.sensor == \"traffic\"\r\n  )\r\n  |> max()"
    },
    {
     "query": "threshold =\r\n  from(bucket: \"smartcity-bucket\")\r\n    |> range(start: -30d)\r\n    |> filter(fn: (r) =>\r\n      r._measurement == \"smartcity_config\" and\r\n      r._field == \"traffic\"\r\n    )\r\n    |> last()\r\n\r\nstart =\r\n  threshold\r\n    |> map(fn: (r) => ({\r\n        _time: v.timeRangeStart,\r\n        _value: r._value\r\n    }))\r\n\r\nstop =\r\n  threshold\r\n    |> map(fn: (r) => ({\r\n        _time: v.timeRangeStop,\r\n        _value: r._value\r\n    }))\r\n\r\nunion(tables: [start, stop])\r\n"
    }
   ]
  },
  { "title": "Noise", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Noise ",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "dB" } },
   "targets": [
    {
     "query": "from(bucket: \"smartcity-bucket\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"smartcity_sensors\" and\r\n    r.district == \"${district}\" and\r\n    r.street == \"${street}\" and\r\n    r.sensor == \"noise\" and\r\n    r._field == \"value\"\r\n  )\r\n"
    },
    {
     "query": "threshold =\r\n  from(bucket: \"smartcity-bucket\")\r\n    |> range(start: -30d)\r\n    |> filter(fn: (r) =>\r\n      r._measurement == \"smartcity_config\" and\r\n      r._field == \"noise\"\r\n    )\r\n    |> last()\r\n\r\nstart =\r\n  threshold\r\n    |> map(fn: (r) => ({\r\n        _time: v.timeRangeStart,\r\n        _value: r._value\r\n    }))\r\n\r\nstop =\r\n  threshold\r\n    |> map(fn: (r) => ({\r\n        _time: v.timeRangeStop,\r\n        _value: r._value\r\n    }))\r\n\r\nunion(tables: [start, stop])\r\n"
    }
   ]
  },
  {
   "title": "Current Noise ",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "dB" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"smartcity-bucket\")\r\n  |> range(start: -5m)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"smartcity_sensors\" and\r\n    r.district == \"${district}\" and\r\n    r.street == \"${street}\" and\r\n    r.sensor == \"noise\"\r\n  )\r\n  |> last()\r\n"
    },
    {
     "query": "threshold =\r\n  from(bucket: \"smartcity-bucket\")\r\n    |> range(start: -30d)\r\n    |> filter(fn: (r) =>\r\n      r._measurement == \"smartcity_config\" and\r\n      r._field == \"noise\"\r\n    )\r\n    |> last()\r\n\r\nstart =\r\n  threshold\r\n    |> map(fn: (r) => ({\r\n        _time: v.timeRangeStart,\r\n        _value: r._value\r\n    }))\r\n\r\nstop =\r\n  threshold\r\n    |> map(fn: (r) => ({\r\n        _time: v.timeRangeStop,\r\n        _value: r._value\r\n    }))\r\n\r\nunion(tables: [start, stop])\r\n"
    }
   ]
  },
  {
   "title": "Mean Noise",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "dB" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"smartcity-bucket\")\r\n  |> range(start: v.timeRangeStart)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"smartcity_sensors\" and\r\n    r.district == \"${district}\" and\r\n    r.street == \"${street}\" and\r\n    r.sensor == \"noise\"\r\n  )\r\n  |> mean()"
    },
    {
     "query": "threshold =\r\n  from(bucket: \"smartcity-bucket\")\r\n    |> range(start: -30d)\r\n    |> filter(fn: (r) =>\r\n      r._measurement == \"smartcity_config\" and\r\n      r._field == \"noise\"\r\n    )\r\n    |> last()\r\n\r\nstart =\r\n  threshold\r\n    |> map(fn: (r) => ({\r\n        _time: v.timeRangeStart,\r\n        _value: r._value\r\n    }))\r\n\r\nstop =\r\n  threshold\r\n    |> map(fn: (r) => ({\r\n        _time: v.timeRangeStop,\r\n        _value: r._value\r\n    }))\r\n\r\nunion(tables: [start, stop])\r\n"
    }
   ]
  },
  {
   "title": "Min Noise",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "dB" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"smartcity-bucket\")\r\n  |> range(start: v.timeRangeStart)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"smartcity_sensors\" and\r\n    r.district == \"${district}\" and\r\n    r.street == \"${street}\" and\r\n    r.sensor == \"noise\"\r\n  )\r\n  |> min()"
    },
    {
     "query": "threshold =\r\n  from(bucket: \"smartcity-bucket\")\r\n    |> range(start: -30d)\r\n    |> filter(fn: (r) =>\r\n      r._measurement == \"smartcity_config\" and\r\n      r._field == \"noise\"\r\n    )\r\n    |> last()\r\n\r\nstart =\r\n  threshold\r\n    |> map(fn: (r) => ({\r\n        _time: v.timeRangeStart,\r\n        _value: r._value\r\n    }))\r\n\r\nstop =\r\n  threshold\r\n    |> map(fn: (r) => ({\r\n        _time: v.timeRangeStop,\r\n        _value: r._value\r\n    }))\r\n\r\nunion(tables: [start, stop])\r\n"
    }
   ]
  },
  {
   "title": "Max Noise",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "dB" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"smartcity-bucket\")\r\n  |> range(start: v.timeRangeStart)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"smartcity_sensors\" and\r\n    r.district == \"${district}\" and\r\n    r.street == \"${street}\" and\r\n    r.sensor == \"noise\"\r\n  )\r\n  |> max()"
    },
    {
     "query": "threshold =\r\n  from(bucket: \"smartcity-bucket\")\r\n    |> range(start: -30d)\r\n    |> filter(fn: (r) =>\r\n      r._measurement == \"smartcity_config\" and\r\n      r._field == \"noise\"\r\n    )\r\n    |> last()\r\n\r\nstart =\r\n  threshold\r\n    |> map(fn: (r) => ({\r\n        _time: v.timeRangeStart,\r\n        _value: r._value\r\n    }))\r\n\r\nstop =\r\n  threshold\r\n    |> map(fn: (r) => ({\r\n        _time: v.timeRangeStop,\r\n        _value: r._value\r\n    }))\r\n\r\nunion(tables: [start, stop])\r\n"
    }
   ]
  },
  { "title": "Temperature", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "Temperature ",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "query": "from(bucket: \"smartcity-bucket\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"smartcity_sensors\" and\r\n    r.district == \"${district}\" and\r\n    r.street == \"${street}\" and\r\n    r.sensor == \"temperature\" and\r\n    r._field == \"value\"\r\n  )\r\n"
    },
    {
     "query": "threshold =\r\n  from(bucket: \"smartcity-bucket\")\r\n    |> range(start: -30d)\r\n    |> filter(fn: (r) =>\r\n      r._measurement == \"smartcity_config\" and\r\n      r._field == \"temperature\"\r\n    )\r\n    |> last()\r\n\r\nstart =\r\n  threshold\r\n    |> map(fn: (r) => ({\r\n        _time: v.timeRangeStart,\r\n        _value: r._value\r\n    }))\r\n\r\nstop =\r\n  threshold\r\n    |> map(fn: (r) => ({\r\n        _time: v.timeRangeStop,\r\n        _value: r._value\r\n    }))\r\n\r\nunion(tables: [start, stop])\r\n"
    }
   ]
  },
  {
   "title": "Current Temperature",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"smartcity-bucket\")\r\n  |> range(start: -5m)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"smartcity_sensors\" and\r\n    r.district == \"${district}\" and\r\n    r.street == \"${street}\" and\r\n    r.sensor == \"temperature\"\r\n  )\r\n  |> last()\r\n"
    },
    {
     "query": "threshold =\r\n  from(bucket: \"smartcity-bucket\")\r\n    |> range(start: -30d)\r\n    |> filter(fn: (r) =>\r\n      r._measurement == \"smartcity_config\" and\r\n      r._field == \"temperature\"\r\n    )\r\n    |> last()\r\n\r\nstart =\r\n  threshold\r\n    |> map(fn: (r) => ({\r\n        _time: v.timeRangeStart,\r\n        _value: r._value\r\n    }))\r\n\r\nstop =\r\n  threshold\r\n    |> map(fn: (r) => ({\r\n        _time: v.timeRangeStop,\r\n        _value: r._value\r\n    }))\r\n\r\nunion(tables: [start, stop])\r\n"
    }
   ]
  },
  {
   "title": "Mean Temperature",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"smartcity-bucket\")\r\n  |> range(start: v.timeRangeStart)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"smartcity_sensors\" and\r\n    r.district == \"${district}\" and\r\n    r.street == \"${street}\" and\r\n    r.sensor == \"temperature\"\r\n  )\r\n  |> mean()"
    },
    {
     "query": "threshold =\r\n  from(bucket: \"smartcity-bucket\")\r\n    |> range(start: -30d)\r\n    |> filter(fn: (r) =>\r\n      r._measurement == \"smartcity_config\" and\r\n      r._field == \"temperature\"\r\n    )\r\n    |> last()\r\n\r\nstart =\r\n  threshold\r\n    |> map(fn: (r) => ({\r\n        _time: v.timeRangeStart,\r\n        _value: r._value\r\n    }))\r\n\r\nstop =\r\n  threshold\r\n    |> map(fn: (r) => ({\r\n        _time: v.timeRangeStop,\r\n        _value: r._value\r\n    }))\r\n\r\nunion(tables: [start, stop])\r\n"
    }
   ]
  },
  {
   "title": "Min Temperature",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"smartcity-bucket\")\r\n  |> range(start: v.timeRangeStart)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"smartcity_sensors\" and\r\n    r.district == \"${district}\" and\r\n    r.street == \"${street}\" and\r\n    r.sensor == \"temperature\"\r\n  )\r\n  |> min()"
    },
    {
     "query": "threshold =\r\n  from(bucket: \"smartcity-bucket\")\r\n    |> range(start: -30d)\r\n    |> filter(fn: (r) =>\r\n      r._measurement == \"smartcity_config\" and\r\n      r._field == \"temperature\"\r\n    )\r\n    |> last()\r\n\r\nstart =\r\n  threshold\r\n    |> map(fn: (r) => ({\r\n        _time: v.timeRangeStart,\r\n        _value: r._value\r\n    }))\r\n\r\nstop =\r\n  threshold\r\n    |> map(fn: (r) => ({\r\n        _time: v.timeRangeStop,\r\n        _value: r._value\r\n    }))\r\n\r\nunion(tables: [start, stop])\r\n"
    }
   ]
  },
  {
   "title": "Max Temperature",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"smartcity-bucket\")\r\n  |> range(start: v.timeRangeStart)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"smartcity_sensors\" and\r\n    r.district == \"${district}\" and\r\n    r.street == \"${street}\" and\r\n    r.sensor == \"temperature\"\r\n  )\r\n  |> max()"
    },
    {
     "query": "threshold =\r\n  from(bucket: \"smartcity-bucket\")\r\n    |> range(start: -30d)\r\n    |> filter(fn: (r) =>\r\n      r._measurement == \"smartcity_config\" and\r\n      r._field == \"temperature\"\r\n    )\r\n    |> last()\r\n\r\nstart =\r\n  threshold\r\n    |> map(fn: (r) => ({\r\n        _time: v.timeRangeStart,\r\n        _value: r._value\r\n    }))\r\n\r\nstop =\r\n  threshold\r\n    |> map(fn: (r) => ({\r\n        _time: v.timeRangeStop,\r\n        _value: r._value\r\n    }))\r\n\r\nunion(tables: [start, stop])\r\n"
    }
   ]
  },
  { "title": "Humidity", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 } },
  {
   "title": "Humidity",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "targets": [
    {
     "query": "from(bucket: \"smartcity-bucket\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"smartcity_sensors\" and\r\n    r.district == \"${district}\" and\r\n    r.street == \"${street}\" and\r\n    r.sensor == \"humidity\" and\r\n    r._field == \"value\"\r\n  )\r\n"
    },
    {
     "query": "threshold =\r\n  from(bucket: \"smartcity-bucket\")\r\n    |> range(start: -30d)\r\n    |> filter(fn: (r) =>\r\n      r._measurement == \"smartcity_config\" and\r\n      r._field == \"humidity\"\r\n    )\r\n    |> last()\r\n\r\nstart =\r\n  threshold\r\n    |> map(fn: (r) => ({\r\n        _time: v.timeRangeStart,\r\n        _value: r._value\r\n    }))\r\n\r\nstop =\r\n  threshold\r\n    |> map(fn: (r) => ({\r\n        _time: v.timeRangeStop,\r\n        _value: r._value\r\n    }))\r\n\r\nunion(tables: [start, stop])\r\n"
    }
   ]
  },
  {
   "title": "Currrent Humidity",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"smartcity-bucket\")\r\n  |> range(start: -5m)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"smartcity_sensors\" and\r\n    r.district == \"${district}\" and\r\n    r.street == \"${street}\" and\r\n    r.sensor == \"humidity\"\r\n  )\r\n  |> last()\r\n"
    },
    {
     "query": "threshold =\r\n  from(bucket: \"smartcity-bucket\")\r\n    |> range(start: -30d)\r\n    |> filter(fn: (r) =>\r\n      r._measurement == \"smartcity_config\" and\r\n      r._field == \"humidity\"\r\n    )\r\n    |> last()\r\n\r\nstart =\r\n  threshold\r\n    |> map(fn: (r) => ({\r\n        _time: v.timeRangeStart,\r\n        _value: r._value\r\n    }))\r\n\r\nstop =\r\n  threshold\r\n    |> map(fn: (r) => ({\r\n        _time: v.timeRangeStop,\r\n        _value: r._value\r\n    }))\r\n\r\nunion(tables: [start, stop])\r\n"
    }
   ]
  },
  {
   "title": "Mean Humidity",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"smartcity-bucket\")\r\n  |> range(start: v.timeRangeStart)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"smartcity_sensors\" and\r\n    r.district == \"${district}\" and\r\n    r.street == \"${street}\" and\r\n    r.sensor == \"humidity\"\r\n  )\r\n  |> mean()"
    },
    {
     "query": "threshold =\r\n  from(bucket: \"smartcity-bucket\")\r\n    |> range(start: -30d)\r\n    |> filter(fn: (r) =>\r\n      r._measurement == \"smartcity_config\" and\r\n      r._field == \"humidity\"\r\n    )\r\n    |> last()\r\n\r\nstart =\r\n  threshold\r\n    |> map(fn: (r) => ({\r\n        _time: v.timeRangeStart,\r\n        _value: r._value\r\n    }))\r\n\r\nstop =\r\n  threshold\r\n    |> map(fn: (r) => ({\r\n        _time: v.timeRangeStop,\r\n        _value: r._value\r\n    }))\r\n\r\nunion(tables: [start, stop])\r\n"
    }
   ]
  },
  {
   "title": "Min Humidity",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"smartcity-bucket\")\r\n  |> range(start: v.timeRangeStart)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"smartcity_sensors\" and\r\n    r.district == \"${district}\" and\r\n    r.street == \"${street}\" and\r\n    r.sensor == \"humidity\"\r\n  )\r\n  |> min()"
    },
    {
     "query": "threshold =\r\n  from(bucket: \"smartcity-bucket\")\r\n    |> range(start: -30d)\r\n    |> filter(fn: (r) =>\r\n      r._measurement == \"smartcity_config\" and\r\n      r._field == \"humidity\"\r\n    )\r\n    |> last()\r\n\r\nstart =\r\n  threshold\r\n    |> map(fn: (r) => ({\r\n        _time: v.timeRangeStart,\r\n        _value: r._value\r\n    }))\r\n\r\nstop =\r\n  threshold\r\n    |> map(fn: (r) => ({\r\n        _time: v.timeRangeStop,\r\n        _value: r._value\r\n    }))\r\n\r\nunion(tables: [start, stop])\r\n"
    }
   ]
  },
  {
   "title": "Max Humidity",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"smartcity-bucket\")\r\n  |> range(start: v.timeRangeStart)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"smartcity_sensors\" and\r\n    r.district == \"${district}\" and\r\n    r.street == \"${street}\" and\r\n    r.sensor == \"humidity\"\r\n  )\r\n  |> max()"
    },
    {
     "query": "threshold =\r\n  from(bucket: \"smartcity-bucket\")\r\n    |> range(start: -30d)\r\n    |> filter(fn: (r) =>\r\n      r._measurement == \"smartcity_config\" and\r\n      r._field == \"humidity\"\r\n    )\r\n    |> last()\r\n\r\nstart =\r\n  threshold\r\n    |> map(fn: (r) => ({\r\n        _time: v.timeRangeStart,\r\n        _value: r._value\r\n    }))\r\n\r\nstop =\r\n  threshold\r\n    |> map(fn: (r) => ({\r\n        _time: v.timeRangeStop,\r\n        _value: r._value\r\n    }))\r\n\r\nunion(tables: [start, stop])\r\n"
    }
   ]
  }
 ]
}